### ISSUE TITLE
鼠标指针

### ISSUE THREAD

**Issue by whckcs** [Yue-plus/Yue-plus#1]
你好大佬，我觉得你Arknights这个博客里的鼠标指针很有意思，可不可以独立做一个

**Comment by Yue-plus** [comment]
独立做一个是指发个npm包？
还是做一个系统光标样式？

**Comment by Yue-plus** [comment]
@ToUNVRSe

**Comment by Yue-plus** [comment]
[ToUNVRSe/arknights-cursor](https://github.com/ToUNVRSe/arknights-cursor)
