### ISSUE TITLE
主题

### ISSUE THREAD

**Issue by whckcs** [Yue-plus/Yue-plus#2]
大佬，你的主题里没有config配置文件，是要自己新建吗

**Comment by Yue-plus** [comment]
[hexo 分支的 _config.arknights.yml](https://github.com/Yue-plus/hexo-theme-arknights/blob/hexo/_config.arknights.yml)

**Comment by whckcs** [comment]
哈哈哈看到了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yue-plus/Yue-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yue-plus/Yue-plus] 主题 (Issue #2)





 
hexo 分支的 _config.arknights.yml
