### ISSUE TITLE
搜索

### ISSUE THREAD

**Issue by whckcs** [Yue-plus/Yue-plus#3]
大佬数据检索功能好像用不了啊，包括你的，搜索不到东西

**Comment by Yue-plus** [comment]
这是个已知问题，现在还没搞。
你可以先用 main 分支的代码。

然后要安装下依赖：


npm: `cnpm install hexo-generator-searchdb --save`

或

yarn: `yarn add hexo-generator-searchdb`

**Comment by whckcs** [comment]
好的我看看






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yue-plus/Yue-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yue-plus/Yue-plus] 搜索 (Issue #3)





 
这是个已知问题，现在还没搞。
 你可以先用 main 分支的代码。
 
然后要安装下依赖：
 
npm: cnpm install hexo-generator-searchdb --save
 
或
 
yarn: yarn add hexo-generator-searchdb
