### ISSUE TITLE
移动端

### ISSUE THREAD

**Issue by whckcs** [Yue-plus/Yue-plus#4]
还有一个问题，移动端上文章点了没反应

**Comment by Yue-plus** [comment]
抱歉，这应该是个bug

![LH7(S 7HF61T84Y91 UYGJM](https://user-images.githubusercontent.com/33195150/194751176-cb64da95-f804-4af5-8570-2f6768e7ba8e.gif)

**Comment by whckcs** [comment]
哈哈哈好的没事




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yue-plus/Yue-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 晚上6:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yue-plus/Yue-plus] 移动端 (Issue #4)





 
抱歉，这应该是个bug

**Comment by whckcs** [comment]
是什么原因



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月9日(周日) 晚上6:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Yue-plus/Yue-plus] 移动端 (Issue #4)




 
抱歉，这应该是个bug

**Comment by Yue-plus** [comment]
这个 Bug 已经修复了，请从 main 分支拉取最新代码。
