### ISSUE TITLE
主题修改

### ISSUE THREAD

**Issue by whckcs** [Yue-plus/Yue-plus#5]
https://laurenfrost.github.io/
还有我想问一下上面这位把导航改到头部是怎么做到的，还有貌似这个没有移动端bug

**Comment by Yue-plus** [comment]
那个是 [1.15.2](https://github.com/Yue-plus/hexo-theme-arknights/releases/tag/1.15.2) 老版本的。
你可以在主题目录下执行 `git checkout 1.15.2` 切换版本

——新功能新 bug

Orz

**Comment by whckcs** [comment]
哦哦，原来如此，谢谢
大佬回复很及时，如果我有能力也想参与到开发中来哈哈哈
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yue-plus/Yue-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 晚上8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yue-plus/Yue-plus] 主题修改 (Issue #5)





 
那个是 1.15.2 老版本的。
 你可以在主题目录下执行 git checkout 1.15.2 切换版本
 
——新功能新 bug
 
Orz

**Comment by whckcs** [comment]
提示这个


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yue-plus/Yue-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 晚上8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yue-plus/Yue-plus] 主题修改 (Issue #5)





 
那个是 1.15.2 老版本的。
 你可以在主题目录下执行 git checkout 1.15.2 切换版本
 
——新功能新 bug
 
Orz

**Comment by Yue-plus** [comment]
> 提示这个
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Yue-plus/Yue-plus" ***@***.***&gt;; 发送时间:&nbsp;2022年10月9日(星期天) 晚上8:39 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Yue-plus/Yue-plus] 主题修改 (Issue #5) 那个是 1.15.2 老版本的。 你可以在主题目录下执行 git checkout 1.15.2 切换版本 ——新功能新 bug Orz — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

提示啥？

**Comment by Yue-plus** [comment]
这个 Issue 因为太久没有回复所以关闭。
