### ISSUE TITLE
bug好了

### ISSUE THREAD

**Issue by whckcs** [Yue-plus/Yue-plus#6]
现在移动端可以进入文章了

**Comment by whckcs** [comment]
哦哦，好像是因为我版本换了，但导航栏和新版的一样，我还以为没换过来

**Comment by Yue-plus** [comment]
我不太记得导航栏是什么时候改的了

你可以翻翻 [releases](https://github.com/Yue-plus/hexo-theme-arknights/releases)

**Comment by whckcs** [comment]
好，话说这个主题可以显示封面图吗，我的banner和cover参数没生效


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yue-plus/Yue-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yue-plus/Yue-plus] bug好了 (Issue #6)





 
我不太记得导航栏是什么时候改的了
 
你可以翻翻 releases

**Comment by Yue-plus** [comment]
封面图写在 `<!-- more -->` 之前。

参考 [README.md](https://github.com/Yue-plus/hexo-theme-arknights#%E5%86%99%E4%BD%9C)

——另外 README.md 最下面有个 QQ 群，有兴趣可以加一下。

**Comment by whckcs** [comment]
ok，我加了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yue-plus/Yue-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 晚上10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yue-plus/Yue-plus] bug好了 (Issue #6)





 
封面图写在 <!-- more --&gt; 之前。
 
参考 README.md
 
——另外 README.md 最下面有个 QQ 群，有兴趣可以加一下。
